---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: buildah-run
spec:
  taskRef:
    name: mybuildah
  outputs:
    resources:
      - name: image
        resourceRef:
          name: image
  inputs:
    resources:
      - name: source
        resourceRef:
          name: nocode
    params:
      - name: TLSVERIFY
        value: "false"
