---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: buildah-run
spec:
  taskRef:
    name: mybuildah
  outputs:
    resources:
      - name: icndb-image
        resourceRef:
          name: icndb-image
  inputs:
    resources:
      - name: icndb-source
        resourceRef:
          name: icndb-source
    params:
      - name: TLSVERIFY
        value: "false"
