apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: icndb-run
spec:
  pipelineRef:
    name: app-deploy
  resources:
    - name: nocode
      resourceRef:
        name: nocode
    - name: image
      resourceRef:
        name: image
