apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: icndb-run
spec:
  pipelineRef:
    name: app-deploy
  resources:
    - name: api-repo
      resourceRef:
        name: api-repo
    - name: api-image
      resourceRef:
        name: api-image
  params:
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc:5000/icndb/api
    - name: imageTag
      value: "1.0"
