apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  resources:
    - name: nocode
      type: git
    - name: image
      type: image
  tasks:
    - name: buildah-run
      taskRef:
        name: mybuildah
      resources:
        inputs:
          - name: source
            resource: nocode
        outputs:
          - name: image
            resource: image
      params:
        - name: TLSVERIFY
          value: "false"

    - name: apply-api-manifests
      taskRef:
        name: apply-manifests
      resources:
        inputs:
          - name: source
            resource: nocode
      runAfter:
        - buildah-run

    - name: update-api-image
      taskRef:
        name: update-deployment
      resources:
        inputs:
          - name: image
            resource: image
      params:
        - name: deployment
          value: "icndb-server"
      runAfter:
        - apply-api-manifests
