---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: icndb-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/nikhil-thomas/icndp-app.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: icndb-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/icndb/api:latest
