apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: update-deployment
spec:
  inputs:
    resources:
      - { type: image, name: image }
    params:
      - name: container-name
        description: The name of the deployment patch the image
        type: string
      - name: deployment-name
        type: string

  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc patch deployment $(inputs.params.deployment-name) --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.container-name)",
              "image":"$(inputs.resources.image.url)"
            }]
          }}}}'
